trying-to-connect-supabase-psql

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -2,8 +2,6 @@
 
 name: CI
 
-# This is the triggers block.
-# It is used to trigger the workflow when a pull request or push is made to the main branch.
 on:
     pull_request:
         branches:
@@ -13,7 +11,6 @@ on:
         branches:
             - main
 
-# Group multiple jobs in a jobs group.
 jobs:
     build-and-test:
         name: Build the project
@@ -29,19 +26,15 @@ jobs:
             PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
 
         steps:
-            # Checkout the code from the repository
             - name: Checkout Code
               uses: actions/checkout@v3
 
-            # Install dependencies
             - name: Install Dependencies
               run: npm ci
 
-            # Run ESLint
             - name: Run ESLint
               run: npm run lint:check
 
-            # Read Secrets Keys
             - name: Read Secret Keys
               run: |
                   if [ "$DB_NAME" == "postgres" ]; then
@@ -56,15 +49,28 @@ jobs:
                     echo "❌ DB_PASSWORD does not match expected secret"
                   fi
 
-            # Run tests
-            # - name: Test and Coverage
-            #   run: npm run test
+            - name: Start Supabase CLI and PostgreSQL
+              uses: supabase/setup-cli@v1
+              with:
+                  version: latest
 
-            # Build TypeScript
+            - name: Init and Start Supabase
+              run: |
+                  supabase init
+                  supabase db start
+                  if supabase db status | grep -q "is running"; then
+                    echo "✅ Supabase/PostgreSQL database setup successfully"
+                  else
+                    echo "❌ Supabase/PostgreSQL database setup failed"
+                    exit 1
+                  fi
+
+            - name: Test and Coverage
+              run: npm run test
+
             - name: Build TypeScript
               run: npm run build
 
-            # SonarCloud Scan
             - name: SonarCloud Scan
               uses: SonarSource/sonarcloud-github-action@master
               env:
@@ -81,21 +87,17 @@ jobs:
             IMAGE_TAG: build-${{ github.run_number }}
 
         steps:
-            # Checkout the code from the repository
             - name: Checkout Repository
               uses: actions/checkout@v3
 
-            # Log in to Docker Hub
             - name: Log into Docker Hub
               uses: docker/login-action@v1
               with:
                   username: ${{ secrets.DOCKERHUB_USERNAME }}
                   password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-            # Build the Docker image
             - name: Build Docker Image
               run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/prod/Dockerfile .
 
-            # Push the Docker image to Docker Hub
             - name: Push Docker Image to Docker Hub
               run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
